name: build and release

on:
  push:
    tags:
      - '*'

jobs:
  # build-arm-musl:
  #   runs-on: ubuntu-24.04-arm
  #   container: rust:alpine3.22
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Build Rust binaries
  #       run: |
  #         mkdir -p output
  #         rustup component add rustfmt
  #         apk update && apk add --no-cache clang gcc build-base make pkgconf elfutils-dev linux-headers
  #         pwd
  #         ls -la
  #         cargo build --release
  #         cp target/release/landscape-webserver output/landscape-webserver-aarch64-musl
  #         # redirect_pkg_handler
  #         cargo build --package landscape-ebpf --bin redirect_pkg_handler --release
  #         cp target/release/redirect_pkg_handler output/redirect_pkg_handler-aarch64-musl

  #     - name: Upload Rust aarch64 binary
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: landscape-webserver-aarch64-musl
  #         path: output/landscape-webserver-aarch64-musl
      
  #     - name: Upload redirect_pkg_handler aarch64 binary
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: redirect_pkg_handler-aarch64-musl
  #         path: output/redirect_pkg_handler-aarch64-musl
  build-musl:
    runs-on: ubuntu-latest
    container: thisseanzhang/landscape:build_base_musl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Rust binaries
        run: |
          mkdir -p output
          cargo build --release
          cp target/release/landscape-webserver output/landscape-webserver-x86_64-musl
          # redirect_pkg_handler
          cargo build --package landscape-ebpf --bin redirect_pkg_handler --release
          cp target/release/redirect_pkg_handler output/redirect_pkg_handler-x86_64-musl

      - name: Upload Rust x86_64 binary
        uses: actions/upload-artifact@v4
        with:
          name: landscape-webserver-x86_64-musl
          path: output/landscape-webserver-x86_64-musl
      
      - name: Upload redirect_pkg_handler x86_64 binary
        uses: actions/upload-artifact@v4
        with:
          name: redirect_pkg_handler-x86_64-musl
          path: output/redirect_pkg_handler-x86_64-musl

  build-rust:
    runs-on: ubuntu-latest
    container: thisseanzhang/landscape:build_base

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Rust binaries
        run: |
          mkdir -p output
          cargo build --release
          cp target/release/landscape-webserver output/landscape-webserver-x86_64
          cargo build --target aarch64-unknown-linux-gnu --release
          cp target/aarch64-unknown-linux-gnu/release/landscape-webserver output/landscape-webserver-aarch64
          # redirect_pkg_handler
          cargo build --package landscape-ebpf --bin redirect_pkg_handler --release
          cp target/release/redirect_pkg_handler output/redirect_pkg_handler-x86_64
          cargo build --package landscape-ebpf --bin redirect_pkg_handler --target aarch64-unknown-linux-gnu --release
          cp target/aarch64-unknown-linux-gnu/release/redirect_pkg_handler output/redirect_pkg_handler-aarch64

      - name: Upload redirect_pkg_handler x86_64 binary
        uses: actions/upload-artifact@v4
        with:
          name: redirect_pkg_handler-x86_64
          path: output/redirect_pkg_handler-x86_64

      - name: Upload redirect_pkg_handler aarch64 binary
        uses: actions/upload-artifact@v4
        with:
          name: redirect_pkg_handler-aarch64
          path: output/redirect_pkg_handler-aarch64

      - name: Upload Rust x86_64 binary
        uses: actions/upload-artifact@v4
        with:
          name: landscape-webserver-x86_64
          path: output/landscape-webserver-x86_64

      - name: Upload Rust aarch64 binary
        uses: actions/upload-artifact@v4
        with:
          name: landscape-webserver-aarch64
          path: output/landscape-webserver-aarch64

  build-front:
    runs-on: ubuntu-latest
    container: node:18.20.7-alpine3.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend
        run: |
          mkdir -p output
          cd landscape-webui
          yarn install --cache-folder /yarn
          NODE_OPTIONS="--max-old-space-size=1700" yarn build
          mkdir static && mv dist/* static/
          apk add zip
          zip -r ../output/static.zip static

      - name: Upload Frontend ZIP
        uses: actions/upload-artifact@v4
        with:
          name: static.zip
          path: output/static.zip

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build-rust, build-front, build-musl]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download x86_64 binary
        uses: actions/download-artifact@v4
        with:
          name: landscape-webserver-x86_64
          path: output

      - name: Download aarch64 binary
        uses: actions/download-artifact@v4
        with:
          name: landscape-webserver-aarch64
          path: output

      - name: Download frontend static.zip
        uses: actions/download-artifact@v4
        with:
          name: static.zip
          path: output

      - name: Download x86_64 musl redirect_pkg_handler binary
        uses: actions/download-artifact@v4
        with:
          name: redirect_pkg_handler-x86_64-musl
          path: output
      - name: Download x86_64 redirect_pkg_handler binary
        uses: actions/download-artifact@v4
        with:
          name: redirect_pkg_handler-x86_64
          path: output
      - name: Download aarch64 redirect_pkg_handler binary
        uses: actions/download-artifact@v4
        with:
          name: redirect_pkg_handler-aarch64
          path: output

      - name: Generate SHASUM
        run: |
          cd output
          sha256sum * > SHASUM256sum.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Auto-generated release from GitHub Actions.
          prerelease: true
          generate_release_notes: true
          files: |
            output/landscape-webserver-x86_64
            output/landscape-webserver-aarch64
            output/static.zip
            output/SHASUM256sum.txt
            output/redirect_pkg_handler-x86_64
            output/redirect_pkg_handler-x86_64-musl
            output/redirect_pkg_handler-aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
